# Copyright 2017 Eficent Business and IT Consulting Services S.L.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

from odoo import api, models
from odoo.exceptions import UserError
from odoo.tools import float_compare


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    def get_location_dest(self, line):
        """
        Return the destination location based on order type
        """
        if line.order_id.type_id and line.order_id.type_id.location_dest_id:
            return line.order_id.type_id.location_dest_id
        return line.order_id.partner_shipping_id.property_stock_customer

    # @api.model_cr
    def _register_hook(self):

        @api.multi
        def action_launch_stock_rule(self):
            """
            Launch procurement group run method with required/custom fields
            generated by a sale order line; procurement group will launch
            '_run_pull', '_run_buy' or '_run_manufacture'
            depending on the sale order line product rule.
            This function is the exact copy of standard Odoo
            sale_stock.sale_order._action_launch_stock_rule()
            with destination location_id evaluated by get_location_dest() function.
            """
            precision = self.env["decimal.precision"].precision_get(
                "Product Unit of Measure")
            errors = []
            for line in self:
                if line.state != "sale" or line.product_id.type not in ("consu",
                                                                        "product"):
                    continue
                qty = line._get_qty_procurement()
                if float_compare(qty,
                                 line.product_uom_qty,
                                 precision_digits=precision) >= 0:
                    continue

                group_id = line.order_id.procurement_group_id
                if not group_id:
                    group_id = self.env["procurement.group"].create(
                        {
                            "name": line.order_id.name,
                            "move_type": line.order_id.picking_policy,
                            "sale_id": line.order_id.id,
                            "partner_id": line.order_id.partner_shipping_id.id,
                        })
                    line.order_id.procurement_group_id = group_id
                else:
                    # In case the procurement group is already created and the order was
                    # cancelled, we need to update certain values of the group.
                    updated_vals = {}
                    if group_id.partner_id != line.order_id.partner_shipping_id:
                        updated_vals.update(
                            {
                                "partner_id": line.order_id.partner_shipping_id.id
                            })
                    if group_id.move_type != line.order_id.picking_policy:
                        updated_vals.update(
                            {
                                "move_type": line.order_id.picking_policy
                            })
                    if updated_vals:
                        group_id.write(updated_vals)

                values = line._prepare_procurement_values(group_id=group_id)
                product_qty = line.product_uom_qty - qty

                procurement_uom = line.product_uom
                quant_uom = line.product_id.uom_id
                get_param = self.env["ir.config_parameter"].sudo().get_param
                if (
                        procurement_uom.id != quant_uom.id
                        and get_param("stock.propagate_uom") != "1"
                ):
                    product_qty = line.product_uom._compute_quantity(
                        product_qty, quant_uom, rounding_method="HALF-UP")
                    procurement_uom = quant_uom

                try:
                    self.env["procurement.group"].run(
                        line.product_id,
                        product_qty,
                        procurement_uom,
                        self.get_location_dest(line),
                        line.name,
                        line.order_id.name,
                        values)
                except UserError as error:
                    errors.append(error.name)
            if errors:
                raise UserError("\n".join(errors))
            return True

        self._patch_method("_action_launch_stock_rule",
                           action_launch_stock_rule)
        return super()._register_hook()
