{
    "name": "Sale Order Lot Selection",
    "version": "12.0.2.0.2",
    "category": "Sales Management",
    "summary": "Sale Order Lot Selection",
    "author": "Odoo Community Association (OCA),Agile Business Group,SHS-AV s.r.l.",
    "website": "https://www.zeroincombenze.it/crm",
    "development_status": "Alpha",
    "license": "AGPL-3",
    "depends": ["sale_stock"],
    "data": ["view/sale_view.xml"],
    "demo": ["demo/sale_demo.xml"],
    "maintainer": "Antonio M. Vigliotti <antoniomaria.vigliotti@gmail.com>",
    "installable": True,
}
